/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formMaster;
import java.awt.Window;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;

/**
 *
 * @author Raihan
 */
public class FormAnakAsuh extends javax.swing.JFrame {
     private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public String tgl;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form FormAnakAsuh
     */
    public FormAnakAsuh() {
        initComponents();
        dtanggal.setDateFormatString("yyyy-MM-dd");
        aktif();
        datatable();
    }
    
    protected void aktif() {
        int kd = (int)(Math.random()* 999999);
        tid.setText(String.valueOf("AA"+kd));
        tid.setEditable(false);
        tnama.setEnabled(true);
        ttempat.setEnabled(true);
        tayah.setEnabled(true);
        tibu.setEnabled(true);
        tsekolah.setEnabled(true);
        tkelas.setEnabled(true);
        
    }
   
 
    
protected void kosong() {
        tid.setText("");
        tnama.setText("");
        ttempat.setText("");
        rjkp.setSelected(false);
        rjkl.setSelected(true);
        dtanggal.setDate(null);
        tayah.setText("");
        tibu.setText("");
        cbPendidikan.setSelectedIndex(0);
        tsekolah.setText("");
        tkelas.setText("");
        rbyatim.setSelected(true);
        rbdhuafa.setSelected(false);
        }

protected void datatable() {
    Object[] Baris = {"ID Anak", "Nama Anak", "Asal Tempat", "Tanggal Lahir", "Jenis Kelamin", "Nama Ayah", "Nama Ibu","Pendidikan","Nama Sekolah","Kelas","Status"};
    tabmode = new DefaultTableModel(null,Baris);
    tabasu.setModel(tabmode);
    String sql = "select * from anak";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil= stat.executeQuery(sql);
            while(hasil.next()){  
            String a = hasil.getString("id");
            String b = hasil.getString("nama");
            String c = hasil.getString("tempat");
            String d = hasil.getString("tgl_lahir");
            String e = hasil.getString("jenis_kelamin");
            String f = hasil.getString("ayah");
            String g = hasil.getString("ibu");
            String h = hasil.getString("pendidikan");
            String i = hasil.getString("sekolah");
            String j = hasil.getString("kelas");
            String k = hasil.getString("status");
            
            String[] data = {a,b,c,d,e,f,g,h,i,j,k};
            tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    
    }

public void tanggal_lahir() {

    try {
        Connection c = new koneksi().connect();
        Statement stat = c.createStatement();
        String sql = "select * from anak where id = '"+tid.getText()+"'";
        ResultSet r = stat.executeQuery(sql);
        while(r.next()){
            dtanggal.setDate(r.getDate("tgl_lahir"));
        }
    } catch (SQLException e) {
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        rjkl = new javax.swing.JRadioButton();
        rjkp = new javax.swing.JRadioButton();
        tayah = new javax.swing.JTextField();
        lnamaayah = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        lnama = new javax.swing.JLabel();
        dtanggal = new com.toedter.calendar.JDateChooser();
        tibu = new javax.swing.JTextField();
        lnamaibu = new javax.swing.JLabel();
        ljenkel = new javax.swing.JLabel();
        ltanggallahir = new javax.swing.JLabel();
        lasal = new javax.swing.JLabel();
        ttempat = new javax.swing.JTextField();
        btsave = new rojerusan.RSMaterialButtonRectangle();
        btedit = new rojerusan.RSMaterialButtonRectangle();
        btdelete = new rojerusan.RSMaterialButtonRectangle();
        btclear = new rojerusan.RSMaterialButtonRectangle();
        lnamasekolah = new javax.swing.JLabel();
        tsekolah = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabasu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        labelpendidikan = new javax.swing.JLabel();
        cbPendidikan = new javax.swing.JComboBox<>();
        lkelas = new javax.swing.JLabel();
        tkelas = new javax.swing.JTextField();
        lstatus = new javax.swing.JLabel();
        lid = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        rbyatim = new javax.swing.JRadioButton();
        rbdhuafa = new javax.swing.JRadioButton();
        btncetak = new rojerusan.RSMaterialButtonRectangle();
        btnexcel = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(rjkl);
        rjkl.setText("Laki-Laki");
        rjkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjklActionPerformed(evt);
            }
        });

        buttonGroup1.add(rjkp);
        rjkp.setText("Perempuan");
        rjkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjkpActionPerformed(evt);
            }
        });

        tayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tayahActionPerformed(evt);
            }
        });

        lnamaayah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lnamaayah.setText("Nama Ayah");

        lnama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lnama.setText("Nama Anak");

        dtanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtanggalPropertyChange(evt);
            }
        });

        tibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tibuActionPerformed(evt);
            }
        });

        lnamaibu.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lnamaibu.setText("Nama Ibu");

        ljenkel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ljenkel.setText("Jenis Kelamin");

        ltanggallahir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ltanggallahir.setText("Tanggal Lahir");

        lasal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lasal.setText("Asal Tempat");

        ttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttempatActionPerformed(evt);
            }
        });

        btsave.setBackground(new java.awt.Color(16, 150, 72));
        btsave.setText("save");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btedit.setBackground(new java.awt.Color(16, 150, 72));
        btedit.setText("EDIT");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btdelete.setBackground(new java.awt.Color(16, 150, 72));
        btdelete.setText("DELETE");
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(16, 150, 72));
        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        lnamasekolah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lnamasekolah.setText("Nama Sekolah");

        tsekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsekolahActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/illust/books.jpg"))); // NOI18N

        tabasu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabasu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabasuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabasu);

        jPanel5.setBackground(new java.awt.Color(16, 150, 72));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA ANAK ASUH");

        jPanel7.setBackground(new java.awt.Color(16, 150, 72));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(153, 204, 255));
        jLabel13.setForeground(new java.awt.Color(255, 0, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-left.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelpendidikan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelpendidikan.setText("Riwayat Pendidikan");

        cbPendidikan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbPendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TK", "SD", "SMP", "SMA", "KULIAH" }));

        lkelas.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lkelas.setText("Kelas");

        tkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkelasActionPerformed(evt);
            }
        });

        lstatus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lstatus.setText("Status");

        lid.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lid.setText("ID Anak");

        buttonGroup2.add(rbyatim);
        rbyatim.setText("Yatim");
        rbyatim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbyatimActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbdhuafa);
        rbdhuafa.setText("Dhuafa");

        btncetak.setBackground(new java.awt.Color(16, 150, 72));
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        btnexcel.setBackground(new java.awt.Color(16, 150, 72));
        btnexcel.setText("SIMPAN EXCEL");
        btnexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnama)
                            .addComponent(lasal)
                            .addComponent(ltanggallahir)
                            .addComponent(ljenkel)
                            .addComponent(lnamaayah)
                            .addComponent(lnamaibu)
                            .addComponent(lid))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ttempat, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tayah, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tibu, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnamasekolah)
                                    .addComponent(lkelas)
                                    .addComponent(lstatus))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rbyatim)
                                        .addGap(54, 54, 54)
                                        .addComponent(rbdhuafa))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rjkl)
                                .addGap(52, 52, 52)
                                .addComponent(rjkp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ttempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tnama)
                                            .addComponent(lnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lasal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ltanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ljenkel)
                                    .addComponent(rjkp)
                                    .addComponent(rjkl))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lnamaayah)
                                    .addComponent(tayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lnamaibu)
                                    .addComponent(tibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelpendidikan)
                                        .addGap(24, 24, 24)
                                        .addComponent(lnamasekolah)
                                        .addGap(24, 24, 24)
                                        .addComponent(lkelas))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbyatim)
                                        .addComponent(rbdhuafa))
                                    .addComponent(lstatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        this.hide();
        new Beranda().setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void tabasuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabasuMouseClicked
        // TODO add your handling code here:
        int bar = tabasu.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 4).toString();
        String e = tabmode.getValueAt(bar, 5).toString();
        String f = tabmode.getValueAt(bar, 6).toString();
        String g = tabmode.getValueAt(bar, 7).toString();
        String h = tabmode.getValueAt(bar, 8).toString();
        String i = tabmode.getValueAt(bar, 9).toString();
        String j = tabmode.getValueAt(bar, 10).toString();



        tid.setText(a);
        tnama.setText(b);
        ttempat.setText(c);
        tanggal_lahir();
        
        if(d.equals("Laki-laki")) {
            rjkl.setSelected(true);
            rjkp.setSelected(false);
        } else {
            rjkl.setSelected(false);
            rjkp.setSelected(true);
        }
        
        tayah.setText(e);
        tibu.setText(f);
        cbPendidikan.setSelectedItem(g);
        tsekolah.setText(h);
        tkelas.setText(i);
         if(j.equals("Yatim")) {
            rbyatim.setSelected(true);
            rbdhuafa.setSelected(false);
        } else {
            rbyatim.setSelected(false);
            rbdhuafa.setSelected(true);
        }
    }//GEN-LAST:event_tabasuMouseClicked

    private void tsekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsekolahActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        // TODO add your handling code here:
        kosong();
        aktif();
    }//GEN-LAST:event_btclearActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,  "hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = " delete from anak where id = '"+tid.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                tid.requestFocus();
                datatable();
                kosong();
                aktif();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+ e);
            }
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Update anak set nama=?, tempat=?, tgl_lahir=?,jenis_kelamin=?,ayah=?,ibu=?,pendidikan=?,sekolah=?,kelas=?,status=? where id=?";
            PreparedStatement stat = conn.prepareStatement(sql) ;
            stat.setString(1, tnama.getText());
            stat.setString(2, ttempat.getText());
            stat.setString(3, tgl);
            
            String jkel="";
            if(rjkl.isSelected()) jkel="Laki-laki";
            else jkel="Perempuan";
            stat.setString(4,jkel);

            stat.setString(5, tayah.getText());
            stat.setString(6, tibu.getText());
            stat.setString(7, cbPendidikan.getSelectedItem().toString());
            stat.setString(8, tsekolah.getText());
            stat.setString(9, tkelas.getText());

            String stts="";
            if(rbyatim.isSelected()) stts="Yatim";
            else stts="Dhuafa";
            stat.setString(10,stts);

            stat.setString(11, tid.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            tid.requestFocus();
            datatable();
            kosong();
            aktif();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into anak values(?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tid.getText());
            stat.setString(2, tnama.getText());
            stat.setString(3, ttempat.getText());
            stat.setString(4, tgl);
            
            String jkel="";
            if(rjkl.isSelected()) jkel="Laki-laki";
            else jkel="Perempuan";
            stat.setString(5,jkel);

            stat.setString(6, tayah.getText());
            stat.setString(7, tibu.getText());
            stat.setString(8, cbPendidikan.getSelectedItem().toString());
            stat.setString(9, tsekolah.getText());
            stat.setString(10, tkelas.getText());
            
            String stts="";
            if(rbyatim.isSelected()) stts="Yatim";
            else stts="Dhuafa";
            stat.setString(11,stts);
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            tid.requestFocus();
            datatable();
            kosong();
            aktif();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_btsaveActionPerformed

    private void ttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttempatActionPerformed

    private void tibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tibuActionPerformed

    private void dtanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtanggalPropertyChange
        // TODO add your handling code here:
        if(dtanggal.getDate()!= null){
            tgl = format.format(dtanggal.getDate());
        }
    }//GEN-LAST:event_dtanggalPropertyChange

    private void tayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tayahActionPerformed

    private void rjkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjkpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rjkpActionPerformed

    private void rjklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjklActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rjklActionPerformed

    private void tkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkelasActionPerformed

    private void rbyatimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbyatimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbyatimActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
         try {
            Map<String,Object> parameter = new HashMap <String,Object>();
            String RealPath = "lib/";
            parameter.put("RealPath", RealPath);
            File file = new File ("src/Laporan/laporanAnakAsuh.jrxml");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/panti_app","root","");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, con);
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data tidak dapat dicetak!"+ e.getMessage());
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void btnexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcelActionPerformed
       
        JFileChooser filechooser = new JFileChooser();
        Window window = null;
        int action  = filechooser.showSaveDialog(window);
        System.err.println(action);
        if(action != 0){
        JOptionPane.showMessageDialog(null,"Terjadi kesalahan saat mengekspor data ke Excel");
        } else {
            try {
            String fileString = filechooser.getSelectedFile().getAbsolutePath() + ".xlsx";
            TableModel model = tabasu.getModel();
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Data Anak Asuh");
            
//            Membuat header kolom
            Row headerRow = sheet.createRow(0);
            for(int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(model.getColumnName(i));
            }
            
//            Membuat data baris
            for(int i = 0; i < model.getRowCount(); i++){
                Row row = sheet.createRow(i + 1);
                for(int j = 0; j< model.getColumnCount(); j++){
                    Cell cell = row.createCell(j);
                    cell.setCellValue(model.getValueAt(i,j).toString());
                }
            }
            
//            Menyimpan file Excel
            FileOutputStream fileOut = new FileOutputStream(new File(fileString));
            workbook.write(fileOut);
            fileOut.close();
            
            JOptionPane.showMessageDialog(null,"Data berhasil diekspor ke file Excel");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan saat mengekspor data ke Excel"+ e.getMessage());
        }
        }
//            


    }//GEN-LAST:event_btnexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAnakAsuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAnakAsuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAnakAsuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAnakAsuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAnakAsuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btclear;
    private rojerusan.RSMaterialButtonRectangle btdelete;
    private rojerusan.RSMaterialButtonRectangle btedit;
    private rojerusan.RSMaterialButtonRectangle btncetak;
    private rojerusan.RSMaterialButtonRectangle btnexcel;
    private rojerusan.RSMaterialButtonRectangle btsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbPendidikan;
    private com.toedter.calendar.JDateChooser dtanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelpendidikan;
    private javax.swing.JLabel lasal;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel ljenkel;
    private javax.swing.JLabel lkelas;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lnamaayah;
    private javax.swing.JLabel lnamaibu;
    private javax.swing.JLabel lnamasekolah;
    private javax.swing.JLabel lstatus;
    private javax.swing.JLabel ltanggallahir;
    private javax.swing.JRadioButton rbdhuafa;
    private javax.swing.JRadioButton rbyatim;
    private javax.swing.JRadioButton rjkl;
    private javax.swing.JRadioButton rjkp;
    private javax.swing.JTable tabasu;
    private javax.swing.JTextField tayah;
    private javax.swing.JTextField tibu;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tkelas;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tsekolah;
    private javax.swing.JTextField ttempat;
    // End of variables declaration//GEN-END:variables
}
